# Generated by Django 2.2.13 on 2022-04-11 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Название слоя в GeoServer')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('zoom_level', models.FloatField(blank=True, null=True, verbose_name='Уровень Zoomа')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Название слоя в GeoServer')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('zoom_level', models.FloatField(blank=True, null=True, verbose_name='Уровень Zoomа')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Название слоя в GeoServer')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('zoom_level', models.FloatField(blank=True, null=True, verbose_name='Уровень Zoomа')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gisapp.District', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Населённый пункт',
                'verbose_name_plural': 'Населённые пункты',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Название слоя в GeoServer')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('zoom_level', models.FloatField(blank=True, null=True, verbose_name='Уровень Zoomа')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gisapp.Town', verbose_name='Населённый пункт')),
            ],
            options={
                'verbose_name': 'Больница',
                'verbose_name_plural': 'Больницы',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gisapp.Region', verbose_name='Область'),
        ),
    ]
