# Generated by Django 2.2.13 on 2022-04-21 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0002_auto_20220421_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
            },
        ),
        migrations.CreateModel(
            name='ExpensesPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Цель расходов',
                'verbose_name_plural': 'Цели расходов',
            },
        ),
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Источник финансирования',
                'verbose_name_plural': 'Источники финансирования',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Тип услуги',
                'verbose_name_plural': 'Типы услуг',
            },
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Объём (тг)')),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gisapp.FundingSource', verbose_name='Источник финансирования')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gisapp.Hospital', verbose_name='Больница')),
            ],
            options={
                'verbose_name': 'Связь Больница-Финансирование',
                'verbose_name_plural': 'Связи Больница-Финансирование',
                'unique_together': {('funding_source', 'hospital')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Объём (тг)')),
                ('expenses_purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gisapp.ExpensesPurpose', verbose_name='Цель расхода')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gisapp.Hospital', verbose_name='Больница')),
            ],
            options={
                'verbose_name': 'Связь Больница-Расход',
                'verbose_name_plural': 'Связи Больница-Расход',
                'unique_together': {('expenses_purpose', 'hospital')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentHospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gisapp.EquipmentType', verbose_name='Оборудование')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gisapp.Hospital', verbose_name='Больница')),
            ],
            options={
                'verbose_name': 'Связь Больница-Оборудование',
                'verbose_name_plural': 'Связи Больница-Оборудование',
                'unique_together': {('equipment', 'hospital')},
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='equipments',
            field=models.ManyToManyField(through='gisapp.EquipmentHospital', to='gisapp.EquipmentType', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='expenses',
            field=models.ManyToManyField(through='gisapp.Expense', to='gisapp.ExpensesPurpose', verbose_name='Расходы'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='fundings',
            field=models.ManyToManyField(through='gisapp.Funding', to='gisapp.FundingSource', verbose_name='Финансирование'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='service_types',
            field=models.ManyToManyField(to='gisapp.ServiceType', verbose_name='Типы услуг'),
        ),
    ]
