# Generated by Django 2.2.13 on 2022-05-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0004_citizenship_ethnicity_mkbclass_patientstay_surgerytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientstay',
            name='illness_history',
            field=models.PositiveIntegerField(default=0, verbose_name='История болезни'),
            preserve_default=False,
        ),
    ]
