# Generated by Django 2.2.13 on 2022-05-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0005_patientstay_illness_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientstay',
            name='from_hospital',
        ),
        migrations.AddField(
            model_name='patientstay',
            name='from_where',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Кем направлен'),
        ),
    ]
