# Generated by Django 2.2.13 on 2022-05-23 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0006_auto_20220523_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientstay',
            name='from_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_hospital', to='gisapp.Hospital', verbose_name='Больница откуда направили'),
        ),
    ]
