# Generated by Django 2.2.13 on 2022-05-23 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0007_patientstay_from_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientstay',
            name='fix_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fix_hospital', to='gisapp.Hospital', verbose_name='Больница прикрепления'),
        ),
    ]
