# Generated by Django 2.2.13 on 2022-05-23 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0008_patientstay_fix_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='StayProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Профиль случая',
                'verbose_name_plural': 'Профили случаев',
            },
        ),
        migrations.AddField(
            model_name='patientstay',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='gisapp.StayProfile', verbose_name='Профиль'),
            preserve_default=False,
        ),
    ]
