# Generated by Django 2.2.13 on 2022-05-24 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0010_auto_20220523_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='average_yearly_employees',
            field=models.FloatField(blank=True, null=True, verbose_name='Среднегодовая численность работников'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='clinical_rating_fb',
            field=models.FloatField(blank=True, null=True, verbose_name='Клинический рейтинг ФБ'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='clinical_rating_kr',
            field=models.FloatField(blank=True, null=True, verbose_name='Клинический рейтинг КР'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='clinical_rating_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Клинический рейтинг max'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='clinical_rating_stars',
            field=models.FloatField(blank=True, null=True, verbose_name='Клинический рейтинг - Звёзды'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='equipments',
            field=models.ManyToManyField(blank=True, through='gisapp.EquipmentHospital', to='gisapp.EquipmentType', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='expenses',
            field=models.ManyToManyField(blank=True, through='gisapp.Expense', to='gisapp.ExpensesPurpose', verbose_name='Расходы'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='female_patients_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='Доля пациентов-женщин'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='fundings',
            field=models.ManyToManyField(blank=True, through='gisapp.Funding', to='gisapp.FundingSource', verbose_name='Финансирование'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='male_patients_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='Доля пациентов-мужчин'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='management_rating_fb',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг по показателям менеджмента ФБ'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='management_rating_kr',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг по показателям менеджмента КР'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='management_rating_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг по показателям менеджмента max'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='management_rating_stars',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг по показателям менеджмента - Звёзды'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='number_of_bed_places',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество койкомест'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='number_of_doctors_with_category',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество врачей с категорией'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='number_of_doctors_without_category',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество врачей без категории'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='number_of_patients_yearly',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество пациентов за год'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='patients_average_stay_days',
            field=models.FloatField(blank=True, null=True, verbose_name='Среднее время пребывания пациентов'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='service_types',
            field=models.ManyToManyField(blank=True, to='gisapp.ServiceType', verbose_name='Типы услуг'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gisapp.Town', verbose_name='Населённый пункт'),
        ),
    ]
