# Generated by Django 2.2.13 on 2022-05-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0011_auto_20220524_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Название'),
        ),
    ]
