# Generated by Django 2.2.13 on 2022-05-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0012_auto_20220524_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientstay',
            options={'verbose_name': 'Госпитализация', 'verbose_name_plural': 'Госпитализации'},
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('region', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='town',
            unique_together={('district', 'name')},
        ),
    ]
