# Generated by Django 2.2.13 on 2022-06-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0013_auto_20220524_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientstay',
            name='illness_history',
            field=models.CharField(max_length=75, verbose_name='История болезни'),
        ),
    ]
