# Generated by Django 2.2.13 on 2022-06-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0015_auto_20220601_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientstay',
            name='case_id',
            field=models.CharField(max_length=75, verbose_name='ID случая'),
        ),
        migrations.AlterField(
            model_name='patientstay',
            name='rpnID',
            field=models.CharField(max_length=75, verbose_name='rpnID'),
        ),
    ]
