# Generated by Django 2.2.13 on 2022-06-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0016_auto_20220601_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientstay',
            name='benefits',
            field=models.CharField(max_length=150, verbose_name='Льгота'),
        ),
    ]
