# Generated by Django 2.2.13 on 2022-06-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0018_auto_20220601_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientstay',
            name='benefits',
            field=models.CharField(max_length=1500, verbose_name='Льгота'),
        ),
        migrations.AlterField(
            model_name='patientstay',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Диагноз заключительный'),
        ),
        migrations.AlterField(
            model_name='patientstay',
            name='treatment_result',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Выздоровление'), (1, 'Смерть'), (2, 'Без перемен'), (3, 'Ухудшение'), (4, 'Улучшение'), (5, 'Переведен в круглосуточный стационар')], verbose_name='Исход лечения'),
        ),
    ]
