version: '3'
services:
  kibana:
    image: 'kibana:${VERSION}'
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch1:9200
    expose:
      - 5601
    depends_on:
      - elasticsearch1
    networks:
      - esnet
      - network
    restart: always

  hq:
    image: 'elastichq/elasticsearch-hq'
    expose:
      - 5000
    networks:
      - esnet
      - network
    restart: always

networks:
  esnet:
    driver: bridge
